### PR TITLE
Enhance search with headings

### PR DESCRIPTION
**Pull request by finanalyst**

### CODE REVIEW

**Review by rawleyfowler — APPROVED** [review]

**Comment by finanalyst** [comment]
This is not right. The wrong duplicates are removed. So all the 'Method' etc duplicates go, but not the Heading ones. Still working on it

**Comment by finanalyst** [comment]
This seems to work now. Can be seen at new-raku.finanalyst.org

**Comment by 2colours** [comment]
The positive is that it solves the "lack of details" issue in the top search bar. There are a couple of negatives, though, that I see:

- I think the font situation is disturbing, it switches to Times New Roman or something, in the middle of the line. I'm not sure if that's intended but it doesn't seem like an adequate way to highlight that part
- the colon looks kind of like a table cell separator but there are no cells so it kinda moves around. Perhaps it would be nice to have table-like alignment but again, hacking it into the current search might not be worth it
- **I see some `: file title` endings - is that to be expected?** Quite a lot, actually. This may be a bug or incompleteness.
- the extended search is lagging behind - what are the plans with that? Right now the site is in a schizophrenic state where the top search bar is still broken in many regards, however it does more than the so-called "extended search"

So depending on the scope of this PR, this can be either the right change or something is still needed. Especially with the "file title" situation, I'd be curious about the behavior and how it's supposed to be.

**Comment by finanalyst** [comment]
> some : file title endings - is that to be expected?
Yes this is expected. There are three sources of information that is used by the search engine
1. Definitions created from `=head` blocks. These are the 'sub', 'routine'' etc entries. Clicking on the link goes to the heading inside the webpage.
2. The source file titles. Clicking takes you to the page top. This info is identified by 'file title'. May be page title? Or some other information?
3. The Table of Contents data for each file. (This is an addition of mine to the search data, and it is not included in the legacy website or Altai-man's version). Some interesting information can be found in sections that mention a key word, but not elsewhere. This is signaled by 'section in'

I understand that the styling of the 'info' div may not be so good. For the bold text, the font-family goes to initial. This is probably a mistake,

However, styling does seem to me to be a different issue to the information available to the user

**Comment by 2colours** [comment]
> The source file titles. Clicking takes you to the page top. This info is identified by 'file title'. May be page title? Or some other information?

Oh, thank you for clarifying. I thought I had seen some examples where it looked odd to imagine the left handside would be the file itself. Maybe it was just my judgement.

In this case, I would actually not add anything to the entry, it could be just the name, like it used to be.

**Comment by finanalyst** [comment]
@2colours Please look at new-raku.finanalyst.org
Search elements filtered in the menu that link to a file now have no info. Headings and definitions have extra information about which file they appear in.
new-raku is also running with the search bar refactored into another plugin.

**Comment by finanalyst** [comment]
I am merging this PR because no one has objected to the extra information  from headings, so long as they are not duplicates and they appear at the bottom of the menu.

**Pull request merged**
