### PR TITLE
Change to mastodon

### LINKED ISSUE #91: Move from twitter to mastodon
> < @lizmat > at the front page, perhaps change Twitter to Mastodon with https://fosstodon.org/@rakulang as link?

### PR DESCRIPTION
**Pull request by rawleyfowler**
fixes #91

### CODE REVIEW

**Review by coke — COMMENTED** [review]
why the change to .gitignore?

**Comment by rawleyfowler** [comment]
@coke For emacs users like myself, emacs spawns file~ as a fallback if something bad happens. I don't want to commit them.

**Comment by coke** [comment]
You should make that change to your global .gitignore, not the project one.

**Comment by rawleyfowler** [comment]
@coke You are entirely correct. What's funny is I already had this in gitignore global. I must be suffering from friday brain.

**Comment by coke** [comment]
Thanks.

**Pull request merged**
