### PR TITLE
Refactor search function

### PR DESCRIPTION
**Pull request by finanalyst**
This addresses multiple issues, nearly all of those tagged `SEARCH`. The PR:
- introduces a new plugin called `options-search`, which replaces `search-bar` almost seemlessly
- modifies plugin `page-styling` to remove the right-hand tile. This was hidden before. The tile was introduced to provide a frame for the search results to be presented. The approach was not liked, so there is no need to have the HTML for it.
- The options-search search bar contains an icon to the right with an (i) and a tooltip saying search options
- Pressing on the i icon generates a modal frame with the various options available and the short cuts.
- The search is completely refactored. Instead of a JQuery plugin, the Autocomplete.js vanilla function suggested by Altai-Man is used. It is simpler and cleaner than the previous search js.
- The shortcut `Ctrl-F` sets the focus on the search
- The search data is only pulled from the site when the search bar first receives focus. So there is a wait only when a search is desired.
- The search is completely navigable using keyboard keys.
- When a search is completed, the requested page is opened in a new tab by default (an option that can be changed)
- various filters can be applied to the search, with the shortcuts affecting the search in real time.
- option values are all stored locally and affect all searches until changed.
- the search works better in the mobile version (but this probably needs tweaking)

Finally, the new functionality can be seen at [new-raku](https://new-raku.finanalyst.org) No doubt there are things that could be improved. Currently, its necessary to navigate to a search candidate and click, rather than the first candidate being automatically selected. Not sure if this is a bug or a feature.

### CODE REVIEW

**Comment by finanalyst** [comment]
@coke @2colours @lizmat @Altai-man please look at the new search live on [new-raku](https://new-raku.finanalyst.org)
As agreed during the consultation, the proposed changes to the UX were done incrementally, but it was recognised the search change would be a bit larger.

**Comment by coke** [comment]
> * When a search is completed, the requested page is opened in a new tab by default (an option that can be changed)

The derfault seems to be same tab, which IMO is correct.

**Comment by Altai-man** [comment]
It looks quite cool! One minor note, is that me or I cannot select all with Ctrl+A in Firefox?

**Comment by 2colours** [comment]
I think it's good to give it some time; I want to play with it a bit more myself. I agree that it looks nice and quite efficient now. :)

Is it okay to spread the word a bit so that interested people can try this version on your site? I was thinking about dropping the link on IRC and the mailing list where the Raku Study mates usually hang out.

**Comment by finanalyst** [comment]
@Altai-man Ctrl-A opens the contents panel. On the landing page, there is no contents tab, so Ctrl-A has no effect. We could change Ctrl-A to something else. Ctrl-C is used for too much so not good. Maybe Alt-C?

@coke My own preference is for selection to another Tab. The option is easy to change, so its just the default. Its going to be a matter of preference and people are going to differ. What principle can be used?

**Comment by Altai-man** [comment]
>Ctrl-A opens the contents panel. On the landing page, there is no contents tab, so Ctrl-A has no effect. We could change Ctrl-A to something else. Ctrl-C is used for too much so not good. Maybe Alt-C?

Oh, that's interesting usage. To me Ctrl+A is the part of my muscle memory for "select all", similar to Ctrl+C, Ctrl+V, Ctrl+X and other siblings.

Almost all input fields I meet daily support this hotkey in this way. By default, Firefox selects all visible text on the page of no focus, and selects all text in an input if it's focused. So I was surprised to see it doesn't work by default.

However, "select all" is just a part of how I edit (often it is less efficient to use backspace to delete every character one by one, so I select all with Ctrl+A and to backspace once, then type a new thing). I have no statistics if such behavior is common though, I remember my informatics teacher scolding me that it's faster to navigate with arrow keys, do a backspace and fix a typo rather than re-typing a whole word by scratch. :D

My gut feeling is most people whose life is not related to coding/typing would not depend on that, but I have no idea on how prevalent is that with programmers.

Anyway, just my 2c.

**Comment by 2colours** [comment]
I agree, probably we aren't a representative sample but I can't imagine somebody would anticipate or comfortably use a fundamental shortcut with a highly unusual meaning. Ctrl+C/X/V/A/R/W shouldn't be used at the very least, and I tend to use even Ctrl+L or Ctrl+E sometimes for the browser.

**Comment by 2colours** [comment]
Some new things that I noticed:

image

when I get something like this, how can I access the remaining results?

Also, how to get the Google search without opening up that info menu?

How can the info menu opened without pressing the button? Is there a shortcut for that as well?

**Comment by finanalyst** [comment]
@Altai-man  @2colours I agree Ctrl-A should be replaced. And I agree with @2colours that shortcuts should avoid common editing ones.
All the search options have 'Alt-' shortcuts.
How about 'Alt-T' to open the Table of contents?

**Comment by finanalyst** [comment]
@2colours All autocomplete plugins that I am aware of limit the number of candidates. I set the limit to 20. Some table sort functions have a paging option to see other candidates. The current output is a limitation related to the autocomplete.js library used here. 
The work around is to add more letters to the search.
The current output is

**Comment by Altai-man** [comment]
>I agree Ctrl-A should be replaced. And I agree with @2colours that shortcuts should avoid common editing ones.

Cool, glad to see it tweaked!

**Comment by coke** [comment]
> The current output is

?

**Comment by coke** [comment]
> @coke My own preference is for selection to another Tab. The option is easy to change, so its just the default. Its going to be a matter of preference and people are going to differ. What principle can be used?

This isn't just a matter of preference, IMO - clicking on a link in a site has defaulted to opening in the same window for decades, in my experience. (again, IME) The only time it's typical to open a new tab without having the user select that option when clicking, is if you have a web app and have an external link that takes you out of the app. Folks, please speak up if you have a recommendation here.

**Comment by coke** [comment]
> @2colours All autocomplete plugins that I am aware of limit the number of candidates. I set the limit to 20

Can we add a backlog item to have an option to click to a page showing all results in line instead of in the dropdown? (Or a way to page the results in line or on the separate page?)

**Comment by finanalyst** [comment]
@coke @2colours I've been looking at the [configuration documentation for autocomplete](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=navigate) and there do seem to be the hooks for getting more of the 'resultsList'.

Some help in modifying the JS in `Website/plugins/options-search' would be appreciated.

My idea is to intercept 'PageDown' and 'PageUp' keys and for them to move through the items using the MoveTo function in the API.

**Comment by finanalyst** [comment]
@coke I will change the default to open in current tab.

**Comment by finanalyst** [comment]
@coke you said:
> > The current output is
> 
> ?
I don't understand. The comment comes after a small commit to change the icon next to the search bar from a font-awesome info icon, which is an 'i' to a font awesome cogs, which looks like some cogs in gear.

**Comment by coke** [comment]
> @coke you said:
> 
> > > The current output is
> 
> > 
> 
> > ?
> 
> I don't understand. The comment comes after a small commit to change the icon next to the search bar from a font-awesome info icon, which is an 'i' to a font awesome cogs, which looks like some cogs in gear. 
> 
> 

You ended with this in a previous comment, so I was hoping you could explain. I was expecting a picture or some text to follow.

**Comment by finanalyst** [comment]
@coke Options search bar was
image
And after comit is
image

**Comment by finanalyst** [comment]
Latest commits visible on [new-raku eg reference page](https://new-raku.finanalyst.org/reference)

**Comment by finanalyst** [comment]
@2colours @coke Regarding the limitation of matches to 20:
- the partial rendering of matches to 20 is removed, so all matches are rendered

**Comment by finanalyst** [comment]
latest changes visible now on new-raku.
@coke all suggestions about search function to date have now been included.
Please let me know if there are more changes to functionality you think need adding.
Otherwise, I think I have finished what I wanted to do on search. This patch should close about a dozen separate issues labelled 'search'

**Comment by coke** [comment]
@finanalyst - i think this addresses my comments, for sure.

I found a minor issue: search for something, scroll down. cancel search. search for something else: scroll is in same position, you have to manually scroll back up.

**Comment by finanalyst** [comment]
latest version visible on new-raku

@coke changes reset scrolling on new focus and when input changed

Also added feedback about Engine state. Just thought this might be good.

No one seems to disapprove of this new functionality. Can we merge  branch to main? Can we close out the various issues?

**Comment by coke** [comment]
@dontlaugh, @finanalyst - test build failed on the cro tests. finanalyst's site looks good, though.

**Review by dontlaugh — DISMISSED** [review]
Ctrl-F should not focus on search. That's going to hurt a lot of workflows.

`/` is a safer common idiom for focusing the search bar.

Let's also not merge with failing tests. What are our alternatives?

**Comment by dontlaugh** [comment]
Note that I fixed the build by just clicking rebuild. Perhaps the Cro-related failure was just flakiness.

**Comment by coke** [comment]
> Note that I fixed the build by just clicking rebuild.

I couldn't see where to do this.

**Comment by coke** [comment]
> Ctrl-F should not focus on search. That's going to hurt a lot of workflows.

Oh, agreed. I didn't realize this because I'm on a mac, and command-f was still built in search. I think the easy fix here is to make the default to not enable this, and if someone wants it they can turn it on.

**Comment by codesections** [comment]
> Ctrl-F should not focus on search. That's going to hurt a lot of workflows.

+1 to this – and to the general principle of not stomping on built-in shortcuts if at all possible.

Of course, in an _ideal_ world, we'd let users set their own shortcut keys.  I'm not suggesting that we add that now, but it could go on a wish list.

(If we're interested in doing that one day, it might be worth refactoring the [relevant code](https://github.com/Raku/doc-website/pull/298/files#diff-8393dc27cf07fe854afd4bd261cf1aef4c20dde41d21544c776bdbb750b924fdR234-R256) to use an object that maps from assigned-key(s) → command instead of including the commands inline.  That way, as we add new commands, they'll all be in a single place if we later decide to make them configurable.)

**Comment by codesections** [comment]
e

**Comment by patrickbkr** [comment]
I also think we should not touch `CTRL+F`. `/` is the common alternative (e.g. on GitHub).

**Comment by finanalyst** [comment]
@Patrick Böker ***@***.***> Problem with / is that it is
difficult to search for /. Alt-/ would be much easier.

**Comment by finanalyst** [comment]
I suppose we could have some config modal form that is activated from the
navigation->more dropdown.
Default shortcuts could then be over-ridden by the user and put in local
storage.

**Comment by finanalyst** [comment]
Agreed that Ctrl-F is used Elsewhere, it would make sense to unify all
shortcuts to Alt-????

Table of contents is toggled with Alt-T, all search shortcuts are Alt+???

Would there be an objection to Alt-F to focus on search?

**Comment by dontlaugh** [comment]
In many window managers, Alt+F opens the file menu. This could also be a problem for accessibility.

As a practical matter, we could defer this entirely: remove the changes related to keyboard shortcuts. They can be added in a small PR later on if we find a general solution.

**Comment by codesections** [comment]
> I suppose we could have some config modal form that is activated from the navigation->more dropdown. Default shortcuts could then be over-ridden by the user and put in local storage.

Yeah, that's the sort of thing I was imagining.  But I think that's more of a "one day" thing than a "part of this PR" thing (unless you're feeling really ambitious).

>  Problem with `/` is that it is difficult to search for `/`. `Alt-/` would be much easier.

I might be missing something, but why would anyone be likely to search for `/`?  I would imagine that people would be more likely to search for `keyboard shortcuts` or `hotkeys`, etc.

Also, I kind of like how GitHub solves the discoverability issue with `/`: by having the default text in the search bar be "type `/` to search (shown below).

image

> Would there be an objection to Alt-F to focus on search?

> In many window managers, Alt+F opens the file menu. This could also be a problem for accessibility.

Yeah, I was going to mention that too.  In addition to accessibility issues, there are also some setups that hide the menu bar unless it's opened with an `Alt` command.  But I also agree that we could bikeshed about which keyboard shortcuts forever without coming up with ones that are perfect for everyone.

**Comment by codesections** [comment]
(Oh, and on setups where `Alt-f` creates accessibility/other issues, the ToC shortcut of `Alt-t` creates the same issues: it opens the `tools` menu)

**Comment by coke** [comment]
I think there's no good universal answer here, but if there is, we should steal it from someone else who spends a lot of time on UI/UX (like github).

I agree, if we can skip the keyboard shortcuts for now and keep  everything else, the work done so far is a big improvement and I'd love to merge that.

**Comment by 2colours** [comment]
Please no... think of people who don't use US layout and don't make the search open for something as obscure as `/`... it's not just an arbitrary non-alphabetic character and therefore by definition unintuitive but it is essentially a "shortcut" in itself for me, namely shift+6. I prefer any shortcut over non-alphabetic characters that make no logical sense and just happen to be easy to access on the US layout.

By the way, Github actually overrides ctrl+f in its online editor in a somewhat arbitrary fashion... but sure, perhaps it shouldn't trump the browser's search.

**Comment by finanalyst** [comment]
1. Shortcuts are clearly a matter of taste, so nothing is going to satisfy
everyone.
2. Users of this site from a mobile or tablet do not have the search window
open by default (the hamburger needs to be clicked).

So a keyboard shortcut for 'search' is a high priority.

3. Within the search there are options that can be toggled using keyboard
shortcuts. I have found these quite useful (eg changing the loose/strict
filtering, removing/adding 'headers' as a source of information or
removing/adding the extra information) and seeing the result live.

I would prefer to see these shortcuts work by default.

4. The ToC toggle shortcut is not as much a priority but I would like to
have one.

So I propose:
1. Adding a new button under 'navigation bar->more' to turn off all
shortcuts (with the aim of replacing it with a more flexible config panel
in the future). This way if any of the options irritate a user, they can be
removed. A simple on/off is easy to do quickly than a generic config.
For clarity, this would only turn off the keyboard shortcuts and the search
options can still be accessed via the 'cogs' popup panel.
2. Stick with Alt-F for search, Alt-T for ToC, and the current search
options.

When I get the configurable options working, they can then all be switched
off or changed.

I thought about having the 'more' option an opt in (default is no keyboard
shortcuts), rather than opt out (shortcuts are the default), but I think
any new user will play around to see what works before deciding whether the
defaults are annoying.

I can probably do this by the weekend. Not sure when a generic config can
be done.

Richard (finanalyst)

**Comment by codesections** [comment]
> So I propose [the plan]

I like that plan.  It moves us forward and avoids needless bikeshedding.  One minor suggestion:

>   Adding a new button under 'navigation bar->more' to turn off all shortcuts

This should probably have a keyboard shortcut for accessibility reasons.  That way, if the current shortcuts are shadowing anything, someone can disable them without needing a mouse.

> Not sure when a generic config can be done.

No promises, but I might have time to help with this/send in a PR.  It'll give me a chance to see just how rusty my js skills have gotten :grin:

**Comment by finanalyst** [comment]
> Ctrl-F should not focus on search. That's going to hurt a lot of workflows.
> 
> `/` is a safer common idiom for focusing the search bar.
> 
> Let's also not merge with failing tests. What are our alternatives?

'/' has too many negatives. Changing to `Alt-F` for search focus. Plan is for Opting-out of keyboard options. In future all shortcuts will be configurable.

So rejecting review.

**Comment by patrickbkr** [comment]
There should be something hinting at the shortcuts, so that casual users get a chance to know and use them. Greyed out text in the search field (similar to what GitHub does) is a good start. Given there are many shortcuts available there should be some obvious overview where people stumble over. Maybe a button labeled "shortcuts" and having some keyboard keys as an icon in the menubar?

**Comment by finanalyst** [comment]
@patrickbkr All items with shortcuts have a 'title' attribute. When there is a mouse hover, the shortcut is given as a 'tool tip'

**Comment by finanalyst** [comment]
@coke in order to turn off all shortcuts, I am refactoring the 'page-styling' plugin. Should this be made a part of this PR, or a separate PR?
If it is made a separate PR, then the `options-search` can be merged into main. 
Another PR can then be made to enable `options-search` and disable `search-bar`.

**Comment by finanalyst** [comment]
@coke the changes to the page-styling were quite substantial in order to group the keyboard shortcuts together. There was a need to slightly refactor the search to make them consistent.
So all the changes are here in one PR.

The updated behaviour is online at [new-raku eg reference](https://new-raku.finanalyst.org/reference)

Try Alt-T for the ToC, Alt-F for the search. Try toggling the shortcuts off, and then Alt-T will be the browser default.

**Review by dontlaugh — APPROVED** [review]

**Pull request merged**
