### PR TITLE
Clean up Caddyfile

### PR DESCRIPTION
**Pull request by dontlaugh**
Remove unused "named" matcher rule. Fix spacing.

### CODE REVIEW

**Comment by coke** [comment]
Sorry about the conflicts!

**Review by finanalyst — APPROVED** [review]
working for my example on docs.raku.org

**Comment by dontlaugh** [comment]
I swapped tabs for spaces just now while resolving the conflicts

**Comment by coke** [comment]
I would have preferred to resolve the production bug we were in the middle of first.

**Pull request merged**
