### PR TITLE
Fix style issue with boxes/columns on the Programs page

### PR DESCRIPTION
**Pull request by finanalyst**
changes SCSS that is targeted at Program page.
change metadata for Program page to trigger styling. Similar to @Altai-man's suggestion, but not quite the same. Case of diminishing return on time investment to get absolutely the same

### CODE REVIEW

**Comment by finanalyst** [comment]
Screenshot from 2023-03-03 11-37-01

**Review by coke — COMMENTED** [review]
Looks like a lot of whitespace changes.

**Comment by finanalyst** [comment]
@coke seems like the 'extra whitespace' comment is blocking the merge. The new format is better than the existing one. Can we merge this change, and then reassess later?

**Comment by coke** [comment]
The whitespace changes make it very difficult to review the actual content changes. I'm not comfortable doing the merge myself.

I thought we already went through some steps to reduce the number of changes like this when regenerating the css?

**Comment by 2colours** [comment]
Why is the generated CSS checked in anyway? Can't it be generated when necessary?

**Comment by finanalyst** [comment]
@2colours the CSS is served to browsers, but SCSS is easier to write. At some point it has to be generated, but that is another issue from this PR. I'll open an issue about this.

**Comment by rawleyfowler** [comment]
@2colours I agree. The generated CSS should be generated on a per-deploy basis.

**Comment by finanalyst** [comment]
closing because new UX will require different changes

**Pull request closed without merging**
