### PR TITLE
Add Development mode, remove CHANGELOG, revise README

### PR DESCRIPTION
**Pull request by finanalyst**
Development mode is a clone of Website for testing changes. It must be specified when running build-site
The only modification (at this PR) is that html is rendered in `development_rendered_html` CHANGELOG.md and CHANGELOG.rakudoc are removed because they are not used at present. README.rakudoc is amended to reflect Development Mode. Note that README.md is generated from README.rakudoc using `Pod::To::Markdown2`

### CODE REVIEW

**Comment by finanalyst** [comment]
The changes in this PR leave the code for generating the doc-website completely unchanged.
CHANGELOG has not been modified since January. It would be good practice to have a CHANGELOG, and perhaps when we start using Development for testing, and only move tested changes over to Website, we can reinstate a CHANGELOG.

**Review by dontlaugh — CHANGES_REQUESTED** [review]
Let's not get rid of the CHANGELOG. Just because we've been a bit neglectful doesn't mean we should give up on it.

Start by adding a CHANGELOG entry for this PR.

**Comment by dontlaugh** [comment]
Also, this is a lot of duplicated code. Too much, imo. 

Unfortunately, it shouldn't be the responsibility of code checked into this _particular_ repo to facilitate additional pre-production versions of the website. This kind of accomplishes that, but at a high cost.

See my recent comment on #217 ; It will take me a while, but I'm working on a solution that is more artifact-based, relying on container tag names more specific than `latest`, etc. Also I'm hoping that we can deploy something that works for all Raku's websites, not just this on.

**Comment by finanalyst** [comment]
@dontlaugh the build changes you are making address the issue better, I think. So removing this PR altogether

**Pull request closed without merging**
