### PR TITLE
addresses issue #221 & #214

### PR DESCRIPTION
**Pull request by finanalyst**
its a trivial change to add a link.

### CODE REVIEW

**Comment by lizmat** [comment]
FWIW, if @coke can live with transferring issues by other users, I'll be happy change the URL manually to make issues for documentation issues on the doc repo.

OTOH, I'm not sure what would be against having an additional link?

**Comment by coke** [comment]
More links == explaining to the users which links to use, more real estate on the footer.  The text here is the minimum we'd need.

I'm not in favor of the change, but let's put it up for a vote: In favor of the change 👍 , opposed 👎

**Comment by finanalyst** [comment]
I'm agnostic on this. 
- IMHO doesn't matter how much you explain, people (like me) will get it wrong the first couple of times. So there will always be some manual changing.
- But for people who make regular contributions, its sometimes useful to have two links in one place as reference / convenience.

**Comment by finanalyst** [comment]
example is live on [new-raku](https://new-raku.finanalyst.org) header->more->...

**Comment by 2colours** [comment]
I like the change. To not trust the users with being able to tell whether they want to report a website problem or a content problem, sounds really overboard, and the reliance on people dispatching issues afterwards, by hand, can be problematic. The content and the website representation don't even have to be managed by the same people. Also, we won't have more repositories anytime soon.

**Comment by finanalyst** [comment]
@coke what is the status of this PR? Have you looked at how it looks on 'new-raku'? If you still don't like it, then lets delete this PR

**Review by coke — APPROVED** [review]

**Pull request merged**
