### PR TITLE
first attempt to incorporate the CREDITS file and About

### PR DESCRIPTION
**Pull request by finanalyst**
This is mentioned in Discussion #51

A setup plugin takes the contributor information in CREDITS, and creates a virtual file in Cache, which is then rendered as credits.rakudoc. This is referenced in about.rakudoc

### CODE REVIEW

**Comment by coke** [comment]
BTW, I was expecting just a link to the raw CREDITS file. As the file gets longer (e.g. to the docs repo size), this may not scale well.

I can't build the site without re-setting up an Azure VM, so I can't easily see this change until it's deployed somewhere.

**Comment by finanalyst** [comment]
The effect of changes to CREDITS - making it a plain text file, a link in about, and a rendering of the information into a table can be found on new-raku.finanalyst.org

We could make the table searchable

**Comment by coke** [comment]
So with this setup, we're showing only the doc-website CREDITS, and in a table dump that doesn't, in my opinion, add much value over the original list format.

I would recommend eliminating this page entirely, and having a link to each raw CREDITS file (doc & doc-website, noting that one is for content, another is for the site) from the about page.

**Comment by finanalyst** [comment]
> eliminating this page entirely
Do you mean the `about` page? Note that there are two links to `about`, one at the bottom of each page next to the `toggle theme`, and one in the `more` drop down.

An `about` at the bottom of a page seems to be a website convention.

Personally, I think two links in the dropdown would be best, one for **content** using info from the CREDITS file in the `Raku/docs` repo, and another separate one for **tooling** using info from the CREDITS file in this repo

However, the text of the CREDITS file says it should be beautified. My credits-page plugin shows how this 'beautification' could be done.

Not to 'beautify' it seems to me to be a bit wrong.

**Comment by coke** [comment]
Given the haphazard amount of data in each CREDITS files (either an enormous entry or spotty coverage on attributes), I don't think the table version is beautified, and I think coming up with a style that works across both CREDITS files isn't worth it, IMO. Regarding the note in the file, keep in mind that's probably 20+ years old at this point, having been copied around since parrot days.

**Comment by finanalyst** [comment]
@coke said
> probably 20+ years old at this point
Since we are actually giving the whole documentation system a major revamp, maybe we should also change the CREDITS spec. Then we could have CREDITS on both pages.

I think it is a good idea to have CREDITS as a text only file, but no need for so many fields. 

We should reconsider the fields.
snail-mail is now simply not a relevant field. Many people are wary about giving away emails. However, a github nic/ IRC nic / website / blog channel / Instagram / Twitter / Facebook are things people are willing to share.

The note at the top of the CREDITS file is also very dated. And even though I date to the same era, I didnt understand the reference to files in other projects.

**Comment by coke** [comment]
Changing the CREDIT spec is a reasonable ask, but for that I'd defer to a problem-solving ticket REPO that covers credits across raku/ & rakudo/. For us, if we go with just a link, we'll catch up to the standard whatever it is.

**Comment by coke** [comment]
Is this version running somewhere I can see?

**Comment by finanalyst** [comment]
About page has been rewritten. Removing this PR

**Pull request closed without merging**
