### PR TITLE
fix issues #287 #106 styling of index layout

### PR DESCRIPTION
**Pull request by finanalyst**
problem was that within 'categories' the items were being distributed between columns badly, and the border effects were ugly at the top and bottom. The CSS relating to the layout was spread between too many files. The patch
- refactors the SCSS so that all `listf-*` CSS is defined in the listfiles plugin, and removed from the page-styling plugin
- refactors the HTML of the categories
- gets the HTML & CSS to work as required
- removes irc.js - a copy/paste error unnoticed until now
- removes _themes-colors.scss redundant file unused before

### CODE REVIEW

**Comment by finanalyst** [comment]
This PR should be independent of the redistribution PR (#294)

**Comment by coke** [comment]
does this fix the styling issues? the languages page, e.g still has wonky column end/start on your site.

**Comment by finanalyst** [comment]
@coke I built the page for my site, then left for the studio before deploying :( new-raku now has changed CSS. Looks better imho

**Comment by coke** [comment]
Ah, there it is, yes much better!

**Review by coke — APPROVED** [review]

**Pull request merged**
