### PR TITLE
Style typegraphs in dark mode #33

### PR DESCRIPTION
**Pull request by rawleyfowler**
Here's the fancier version:

2023-01-26-185529_1920x1080_scrot

2023-01-26-190756_1920x1080_scrot

### CODE REVIEW

**Comment by 2colours** [comment]
To be honest, I don't really like this "blurple" color for roles on the light theme either - here, I think it's getting disturbing to the eye. Not sure about brown... maybe, since the site is already using the golden yellow-ish color (the color of the Typegraph header), roles could also get that?

**Comment by rawleyfowler** [comment]
@2colours I updated the pr.

**Comment by rawleyfowler** [comment]
I can do the light theme too, if we want it to be colored according to the scheme.

**Comment by 2colours** [comment]
Oh another thing that I very much welcome is that you changed the background to the same color so that it doesn't have a visible border.

**Comment by rawleyfowler** [comment]
I just removed the background completely so it just uses transparency @2colours

**Review by Altai-man — APPROVED** [review]
I'm approving this, but @finanalyst has the final word.

**Comment by finanalyst** [comment]
This looks really good. The config file for the typegraph plugin has a separate authors' key. Would you please add your name to it.

**Comment by rawleyfowler** [comment]
@finanalyst I added my name. Thanks!

**Pull request merged**
